frr version 8.4
frr defaults traditional
hostname router
no ipv6 forwarding
!
interface eth1
 ip address 10.0.1.1/24
 description link-to-network-1
!
interface eth2
 ip address 10.0.2.1/24
 description link-to-network-2
!
line vty
!